# Generated by Django 4.0.7 on 2023-12-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, unique=True)),
                ('slug', models.CharField(max_length=255, null=True, unique=True)),
                ('request', models.CharField(max_length=255, null=True)),
                ('request_type', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('request_input', models.TextField(null=True)),
                ('request_output', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma seperated set of SEO Keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Content for description of meta tag', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeSnippets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('code', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_free', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.endpoints')),
            ],
            options={
                'unique_together': {('api', 'language')},
            },
        ),
    ]
