# Generated by Django 4.0.7 on 2023-10-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_codesnippets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesnippets',
            old_name='description',
            new_name='code',
        ),
    ]
